name: Clear cache by prefix
description: A Github action to delete the cache whose key starts with a specific prefix

branding:
  icon: archive
  color: purple

inputs:
  cache-prefix:
    description: The prefix of the cache keys to delete
    required: true
  github-token:
    description: The GitHub token to use
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clear cache
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          function bytesToHumanReadable(bytes) {
            const kilobytes = bytes / 1024;
            if (kilobytes < 1024) {
              return kilobytes.toFixed(2) + " Ko";
            } else {
              const megabytes = kilobytes / 1024;
              return megabytes.toFixed(2) + " Mo";
            }
          }
          
          const response = await github.rest.actions.getActionsCacheList({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          let totalSizeCleared = 0;
          const caches = response.data.actions_caches;
          for (const cache of caches) {
            const key = cache.key;
            if (key.startsWith('${{ inputs.cache-prefix }}')) {
              const deleteResponse = await github.rest.actions.deleteActionsCacheByKey({
                owner: context.repo.owner,
                repo: context.repo.repo,
                key,
              });
              console.log(`Deleted cache with key: ${ key }, size: ${ cache.size_in_bytes }`);
              totalSizeCleared += cache.size_in_bytes;
            }
          }
          console.log(`Total size cleared: ${ bytesToHumanReadable(totalSizeCleared) } 🚮`);